language: perl
os:
  - linux
dist: trusty
perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.26-shrplib"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
env:
  global:
    - AUTOMATED_TESTING=1
    - TK_TEST_LENGTH=120
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq xvfb
 - Xvfb :123 &
 - export DISPLAY=:123
 - (sleep 10; twm) &
before_install:
  - brew install cpanm                     || true
install:
  - cpanm --quiet --installdeps --notest . || true
notifications:
  irc:
    channels:
      - "irc.perl.org#csv"
    on_success: always
    on_failure: always
